name: Publish 🚀

on:
  workflow_dispatch:
  push:
    branches:
    - main

env:
  AZURE_WEBAPP_NAME_LINUX: dotnet-redm-api-linux
  AZURE_WEBAPP_PACKAGE_PATH_LINUX: "./publish"

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          
      - name: Restore
        run: dotnet restore ./redm-backend.sln
        
      - name: Build
        run: dotnet build ./redm-backend.sln --configuration Release --no-restore
        
      - name: Publish
        run: dotnet publish ./redm-backend.sln --configuration Release --no-build --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH_LINUX }}'
        
      - name: Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME_LINUX }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_LINUX }}
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH_LINUX }}"
